platform :ios, '8.0' 
inhibit_all_warnings!
pod 'AFNetworking', '~> 3.0.4'
pod 'MBProgressHUD'
pod 'NSData+Base64'
pod 'IQKeyboardManager'
pod 'RATreeView'
pod 'BlockInjection'
pod 'LKDBHelper'
pod 'Reachability'
pod 'NSDate+Helper'
pod 'OpenUDID'
pod 'NSDate+Helper'
pod 'UICountingLabel'
pod 'MJPopupViewController'
pod 'HyphenateFullSDK', :git => 'https://github.com/easemob/hyphenate-full-cocoapods.git'
pod 'JZLocationConverter'
pod 'SDWebImage'
